### ISSUE TITLE
PDF not compiling without code block

### ISSUE THREAD

**Issue by THuizinga** [thomfre/OSCP-Exam-Report-Template#2]
The commit _Fixed issue with line breaks in code blocks_ introduces an error when there are no code blocks present in the file to compile. The error is as follows:

```
user@kali-64:~/Documents/OSCP-Exam-Report-Template$ ./generate-report.sh lab-report abc.pdf
[*] Preparing lab report for generation
[*] Stitching together targets, appendices and exercises
[*] Correcting relative image URLs
[*] Generating report
[*] Creating PDF
Error producing PDF.
! LaTeX Error: Command \AlertTok undefined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.328 \begin{document}
```

This showed up when running `generate-report.sh` from the original source. I work around it by creating a code block in the file `Lab/Exercises/1.1.1 Exercise.md` as follows:
````
# Exercise

Exercise here

```c
code here
```
````

**Comment by THuizinga** [comment]
I can create a pull request for this workaround but I would prefer a more elegant solution

**Comment by thomfre** [comment]
Fixed by adding check before reassigning the code block functions.
